name: flutter_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  http: ^0.13.6
  flutter_secure_storage: ^9.0.0
  lucide_icons: ^0.257.0
  cupertino_icons: ^1.0.8
  cryptography: ^2.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/company_logo.png
    - assets/logo/login_image.png
    - assets/logo/logo.png
    - assets/images/customers.png
    - assets/images/orders.png
    - assets/images/resources.png
    - assets/images/help.png
    - assets/images/resource_1.png
    - assets/images/resource_2.png
    - assets/images/resource_3.png
    - assets/images/resource_4.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
